/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //Amazon ama = new Amazon();
            BookMyShow bms = new BookMyShow();
            BmsImage bmi = new BmsImage();
            Likendin lik = new Likendin();
            NestedFrame nest = new NestedFrame();
            Likedinveiw lv = new Likedinveiw();
        //amzon testcase
           // ama.amazon();
           // ama.testCase01();
           // ama.endTest();
             //    bms.bookmyshow();
              //   bms.testCase01();
              //   bms.endTest();
            //   bmi.bms();
            //   bmi.testCase01();
            //   bmi.endTest();
       //bms testcase
    //    lik.likendin();
    //    lik.testCase01();
    //    lik.endTest();
    // nest.NestedFrame();
    // nest.testCase01();
    // // nest.endTest();
    // lv.Likedinveiw();
    // lv.testCase01();
    // lv.endTest();
      
   
    

        
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
