/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //Amazon ama = new Amazon();
            BookMyShow bms = new BookMyShow();
        //amzon testcase
           // ama.amazon();
           // ama.testCase01();
           // ama.endTest();
                 bms.bookmyshow();
                 bms.testCase01();
                 bms.endTest();
       //bms testcase
      
   
    

        
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
